CareJobApplicationv2/Models/ApplicantBrofile.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareJobApplicationv2.Models
{
    public class ApplicantBrofile
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Full Name")]
        [Required(ErrorMessage = "Full name is required")]

        public string FullNameEn { get; set; }

        [Display(Name = "لإسم الكامل")]
        [Required(ErrorMessage = "يرجى إدخال الإسم الكامل ")]

        public string FullNameAr { get; set; }

        [Display(Name = "Birth Date")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Birth Date is required")]
        public DateTime BirthDate { get; set; }


        [Display(Name = "Gender")]
        [Required(ErrorMessage = "Gender Type is required")]
        // public int? GenderId { get; set; }
        [EnumDataType(typeof(Gender))]
        public Gender GenderId { get; set; }

        [Display(Name = "Nationality")]

        public string Nationality { get; set; }

        [Display(Name = "Mobile Number")]
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Phone Number is required")]
        public string MobileNumber { get; set; }


        [Display(Name = "Upload personal Photo")]
        [DataType(DataType.Upload)]

        public string ApplicantPhoto { get; set; }


        [Display(Name = "FieldLable_CurrentAddress")]

        public string Address { get; set; }



        [Display(Name = "Current Address Country")]

        public string Country { get; set; }

        [Display(Name = "Current Address City")]

        public string City { get; set; }

        public string UserId { get; set; }
        
        [DataType("Email")]
        public string Email { get; set; }

        [ForeignKey("UserId")]
        public ApplicationUser ApplicationUser { get; set; }
    }

    public enum Gender
    {
        Male = 1,
        Female = 2
    }
}

CareJobApplicationv2/Models/ApplicantComputerSkills.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareJobApplicationv2.Models
{
    public class ApplicantComputerSkills
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "Skill")]
        
        public int SkillId { get; set; }
        [Display(Name = "Skill level")]
        public int SkillLevelId { get; set; }

        public string UserId { get; set; }

        [ForeignKey("SkillId")]
        public virtual  ComputerSkills ComputerSkills { get; set; }
        [ForeignKey("SkillLevelId")]
        public virtual ComputerSkillLevels ComputerSkillLevels { get; set; } 
    }
}

CareJobApplicationv2/Models/ApplicantDocuments.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareJobApplicationv2.Models
{
    public class ApplicantDocuments
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Document Type")]
        [ForeignKey("DocumentTypes")]
        public int DocumentType { get; set; }


        [DataType(DataType.Upload)]
        public string Document { get; set; }

        
        public string DocumentDescription { get; set; }


        public DateTime CreatedDate { get; set; }

        public string UserId { get; set; }

        public virtual DocumentTypes DocumentTypes { get; set; }
    }
}

CareJobApplicationv2/Models/ApplicantEducations.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CareJobApplicationv2.Models
{
    public class ApplicantEducations
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Education Degree")]
        [Required(ErrorMessage ="Please Select Degree")]
        [ForeignKey("EducationDegree")]
        public int EducationDegreeId { get; set; }

        [Display(Name = "Education Major")]
        [Required(ErrorMessage = "Please Select Major")]
        [ForeignKey("EducationMajor")]
        public int EducationMajorId { get; set; }

        [Display(Name = "Education Country")]
        [Required(ErrorMessage = "Please Select Country of Education")]
        //[ForeignKey("Countries")]
        public string CountryEducation { get; set; }

        [Display(Name = "Institution")]
        [Required(ErrorMessage = "Please write institution ")]
        public string InstitutionEn { get; set; }

        [Display(Name = "إسم المؤسسة التعليمية")]

        public string InstitutionAr { get; set; }

        [Display(Name = "Education Status")]
        [ForeignKey("EducationStatus")]
        public int Status { get; set; }

        [Display(Name = "Year of Starting")]
        [DataType(DataType.Date)]
        public DateTime YearOfStarting { get; set; }

        [Display(Name = "Year of Finished")]
        [DataType(DataType.Date)]
        public DateTime YearOfFinished { get; set; }

        public string UserId { get; set; }

        
        public virtual EducationMajor EducationMajor { get; set; }

        
        public virtual EducationDegree EducationDegree { get; set; }

        public virtual EducationStatus EducationStatus { get; set; }

        //public virtual Countries Countries { get; set; }
    }
}

CareJobApplicationv2/Models/ApplicantExperiences.cs
using System.ComponentModel.DataAnnotations;

namespace CareJobApplicationv2.Models
{
    public class ApplicantExperiences
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Employer name is requierd")]
        public string EmployerName { get; set; }
        [Required(ErrorMessage = "Position is requierd")]
        public string Position { get; set; }
        public string Tasks { get; set; }
        [Required(ErrorMessage ="Start Date is requierd")]
        
        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }
        
        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }
        public string Reasonforleave { get; set; }
        public string UserId { get; set; }


    }
}

CareJobApplicationv2/Models/ApplicantQ1Answers.cs
using System.ComponentModel.DataAnnotations;

namespace CareJobApplicationv2.Models
{
    public class ApplicantQ1Answers
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Person Name")]
        public string PersonNameEn { get; set; }

        [Display(Name = "الاسم")]
        public string personNameAr { get; set; }

        [Display(Name = "Relation Type")]
        public string RelationType { get; set; }

        public string UserId { get; set; }
    }
}

CareJobApplicationv2/Controllers/ApplicantBrofilesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CareJobApplicationv2.Data;
using CareJobApplicationv2.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace CareJobApplicationv2.Controllers
{
    [Authorize(Roles = "Applicant")]
    public class ApplicantBrofilesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public ApplicantBrofilesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: ApplicantBrofiles
        public async Task<IActionResult> Index()
        {
            var CUserId = _userManager.GetUserId(HttpContext.User);
            ViewBag.UserId = CUserId;
            var UserProfiles = await _context.ApplicantBrofile.Where(u => u.UserId == CUserId).ToListAsync();
            return View(UserProfiles);
        }
        public IActionResult userProfile()
        {
            var CUserId = _userManager.GetUserId(HttpContext.User);
            ViewBag.UserId = CUserId;




            //ViewBag.EducationDegree = _context.EducationDegree.OrderBy(x => x.EducationDegreeTitle).ToList();
            // ViewBag.EducationMigor = _context.EducationMajor.OrderBy(x => x.EducationMajorTitle).ToList();

            // ViewBag.userProfile = _context.ApplicantBrofile.SingleOrDefault(u => u.UserId == CUserId);
            // ViewBag.userEducation = _context.ApplicantEducations.Where(u => u.UserId == CUserId).ToList();
            // ViewBag.userLanguage = _context.ApplicantLanguageSkilles.Where(u => u.UserId == CUserId).ToList();
            // ViewBag.userDocuments = _context.ApplicantDocuments.Where(u => u.UserId == CUserId).ToList();
            //ViewBag.userReferee = _context.applicantReferees.Where(u => u.UserId == CUserId).ToList();
            // ViewBag.userQ1Answers = _context.ApplicantQ1Answers.Where(u => u.UserId == CUserId).ToList();
            // ViewBag.userQ2Answers = _context.ApplicantQ2Answers.Where(u => u.UserId == CUserId).ToList();

            var ApplicantBrofile = _context.ApplicantBrofile.FirstOrDefault(u => u.UserId == CUserId);




            return View(ApplicantBrofile);
        }

        public IActionResult GetUserProfile()
        {
            var CUserId = _userManager.GetUserId(HttpContext.User);
            ViewBag.UserId = CUserId;
            ViewBag.ProfileId = 0;
            var userProfile = _context.ApplicantBrofile.SingleOrDefault(u => u.UserId == CUserId);
            if (userProfile == null)
                return View(new ApplicantBrofile());
            // else
            // {
            //     ViewBag.ProfileId = userProfile.Id;
            // }


            return View(userProfile);

        }

        // GET: ApplicantBrofiles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ApplicantBrofile == null)
            {
                return NotFound();
            }

            var applicantBrofile = await _context.ApplicantBrofile
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicantBrofile == null)
            {
                return NotFound();
            }

            return View(applicantBrofile);
        }

        // GET: ApplicantBrofiles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ApplicantBrofiles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullNameEn,FullNameAr,BirthDate,GenderId,Nationality,MobileNumber,ApplicantPhoto,Address,Country,City,UserId")] ApplicantBrofile applicantBrofile)
        {
            if (ModelState.IsValid)
            {
                _context.Add(applicantBrofile);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(applicantBrofile);
        }

        // GET: ApplicantBrofiles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ApplicantBrofile == null)
            {
                return NotFound();
            }

            var applicantBrofile = await _context.ApplicantBrofile.FindAsync(id);
            if (applicantBrofile == null)
            {
                return NotFound();
            }
            return View(applicantBrofile);
        }

        // POST: ApplicantBrofiles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullNameEn,FullNameAr,BirthDate,GenderId,Nationality,MobileNumber,ApplicantPhoto,Address,Country,City,UserId")] ApplicantBrofile applicantBrofile)
        {
            if (id != applicantBrofile.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applicantBrofile);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplicantBrofileExists(applicantBrofile.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(applicantBrofile);
        }

        // GET: ApplicantBrofiles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ApplicantBrofile == null)
            {
                return NotFound();
            }

            var applicantBrofile = await _context.ApplicantBrofile
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applicantBrofile == null)
            {
                return NotFound();
            }

            return View(applicantBrofile);
        }

        // POST: ApplicantBrofiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ApplicantBrofile == null)
            {
                return Problem("Entity set 'ApplicationDbContext.ApplicantBrofile'  is null.");
            }
            var applicantBrofile = await _context.ApplicantBrofile.FindAsync(id);
            if (applicantBrofile != null)
            {
                _context.ApplicantBrofile.Remove(applicantBrofile);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplicantBrofileExists(int id)
        {
            return _context.ApplicantBrofile.Any(e => e.Id == id);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,FullNameEn,FullNameAr,BirthDate,GenderId,Nationality,MobileNumber,ApplicantPhoto,Address,Country,City,UserId")] ApplicantBrofile applicantBrofile)
        public async Task<IActionResult> ProfileCreate(ApplicantBrofile applicantBrofile)
        {


            if (ModelState.IsValid)
            {
                if (applicantBrofile.UserId == null)
                {
                    if (_userManager.GetUserId(HttpContext.User) != null)
                    {
                        applicantBrofile.UserId = _userManager.GetUserId(HttpContext.User);
                    }
                    UploadProfilePhoto(applicantBrofile);

                    //applicantBrofile.UserId = User.Identity.
                    _context.Add(applicantBrofile);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(userProfile));
                }
                else
                {
                    UploadProfilePhoto(applicantBrofile);

                    //applicantBrofile.UserId = User.Identity.
                    _context.Update(applicantBrofile);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(userProfile));
                }
                


            }
            //applicantBrofile
            return View();
            //return PartialView("_ApplicantProfile", applicantBrofile);
        }
        /************************************************************************/
        private void UploadProfilePhoto(ApplicantBrofile applicantBrofile)
        {
            var CurrentFullName = applicantBrofile.FullNameEn;
            var BrofileImageFullName = CurrentFullName.Replace(' ', '-');
            var ProfileImage = HttpContext.Request.Form.Files;
            if (ProfileImage.Count() > 0)
            {
                //upload Profile Image
                string ImageFileName = Guid.NewGuid().ToString() + BrofileImageFullName + Path.GetExtension(ProfileImage[0].FileName);
                var fileStream = new FileStream(Path.Combine(@"wwwroot/", "Images/ProfilePhotos/", ImageFileName), FileMode.Create);
                ProfileImage[0].CopyTo(fileStream);

CareJobApplicationv2/Views/ApplicantBrofiles/AddApplicantEducation.cshtml
@model CareJobApplicationv2.Models.ApplicantEducations

@{
   // ViewData["Title"] = "Create";
    
    Layout = null;

}






<div class="row">
    <div class="col-lg-12">
        <form asp-action="AddApplicantEducation" method="post" onsubmit="return SubmitForm(this,'ApplicantEducation')">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row mt-2 mb-2">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="EducationDegreeId" class="control-label"></label>
                
                        <select asp-for="EducationDegreeId" class="form-select" asp-items="ViewBag.EducationDegreeId">
                            <option value="">Choose a Degree</option>
                        </select>
                        <span asp-validation-for="EducationDegreeId" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="EducationMajorId" class="control-label"></label>
                        <select asp-for="EducationMajorId" class="form-select" asp-items="ViewBag.EducationMajorId" >
                            <option value="">Choose a Major</option>
                        </select>
                        <span asp-validation-for="EducationMajorId" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row mt-2 mb-2">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="CountryEducation" class="control-label"></label>
                        <!--input asp-for="CountryEducation" class="form-control" /-->
                        <select asp-for="CountryEducation" class="form-control" asp-items="ViewBag.EducationCountries">
                            <option value="">Select</option>
                        </select>
                        <!--select asp-for="CountryEducation" class="Form-select" asp-items="ViewBag.ListCountries">
                            <option value="">Choose Country</option>
                        </!--select-->
                        <span asp-validation-for="CountryEducation" class="text-danger"></span>
                
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="InstitutionEn" class="control-label"></label>
                        <input asp-for="InstitutionEn" class="form-control" />
                        <span asp-validation-for="InstitutionEn" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="row mt-2 mb-2">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="InstitutionAr" class="control-label"></label>
                        <input asp-for="InstitutionAr" class="form-control" />
                        <span asp-validation-for="InstitutionAr" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                        <input asp-for="Status" class="form-control" />
                        <select asp-for="CountryEducation" class="form-control" asp-items="ViewBag.EducationStatus">
                            <option value="">Select Status</option>
                        </select>
                        <span asp-validation-for=" Status" class="text-danger">
                            </span>
</div>
                </div>
            </div>
            <div class="row mt-2 mb-2">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="YearOfStarting" class="control-label"></label>
                        <input asp-for="YearOfStarting" class="form-control" />
                        <span asp-validation-for="YearOfStarting" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="YearOfFinished" class="control-label"></label>
                        <input asp-for="YearOfFinished" class="form-control" />
                        <span asp-validation-for="YearOfFinished" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="form-group">
                    <input type="submit" value="Add Education Details" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>




@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CareJobApplicationv2/Views/ApplicantBrofiles/_ApplicantComputerSkills.cshtml
<div class="row text-center mt-5 mb-5">
    

</div>
<div class="row">
    



    <div class="col-lg-12">
        <div class="card mb-4">
           
             <div class="card-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h5 >Languag Skills</h5>
                    </div>
                    <div class="col-sm-4 text-right">
                        <a class="btn btn-sm btn-success" onclick="PopupForm('@Url.Action("AddApplicantComputerSkill","ApplicantBrofiles")','Add New Computer Skills Data', 300, 700)"><i class="fas fa-plus"></i> Add Computer Skills</a>
                    </div>
                </div>
            </div>
             <div class="card-body text-center">
                 <div class="row">
                    <table id="ApplicantComputerSkills" class="table table-striped table-bordered " style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>ComputerSkill</th>
                               
                                <th>Skill</th>
                                
                                <th></th>

                            </tr>
        
                        </thead>
                        <tbody>

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

CareJobApplicationv2/Views/ApplicantBrofiles/_ApplicantDocuments.cshtml
<div class="row text-center mt-5 mb-5">
    

</div>
<div class="row">
    


    
    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h5 >Documents</h5>
                    </div>
                    <div class="col-sm-4 text-right">
                        <a class="btn btn-sm btn-success" onclick="PopupForm('@Url.Action("CreateApplicantDocuments","ApplicantBrofiles")','Add New Document', 280, 700)"><i class="fas fa-plus" ></i> Add Document Details</a>
                    </div>
                </div>
            </div>
            
             <div class="card-body text-center">
                 <div class="row">
                    <table id="ApplicantDocuments" class="table table-striped table-bordered " style="width:100%">
                        

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

CareJobApplicationv2/Views/ApplicantBrofiles/_ApplicantEducation.cshtml
<div class="row text-center mt-5 mb-5">
    
   

</div>
<div class="row">
    

     

    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h5 >Education</h5>
                    </div>
                    <div class="col-sm-4 text-right">
                        <a class="btn btn-success" onclick="PopupForm('@Url.Action("AddApplicantEducation","ApplicantBrofiles")','Education Data', 400, 700)"><i class="fas fa-plus" ></i> Add Education Details</a>
                    </div>
                </div>
            </div>
            
             <div class="card-body text-center">
                 <div class="row">
                    <table id="ApplicantEducation" class="table table-striped table-bordered " style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Degree</th>
                                <th>Major</th>
                                <th>Country</th>
                                <th>Institution</th>
                                <th>Status</th>
                                <th>Started</th>
                                <th>Finished</th>
                                <th></th>
                            </tr>
        
                        </thead>
                        <tbody>

                        </tbody>

                    </table>


                </div>
            </div>
        </div>
    </div>
</div>

CareJobApplicationv2/Views/ApplicantBrofiles/_ApplicantExperience.cshtml
<div class="row text-center mt-5 mb-5">
    

</div>
<div class="row">
    


    
    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h5 >Experiences</h5>
                    </div>
                    <div class="col-sm-4 text-right">
                        <a class="btn btn-sm btn-success" onclick="PopupForm('@Url.Action("CreateApplicantExperiences","ApplicantBrofiles")','Add Experience Data', 280, 700)"><i class="fas fa-plus" ></i> Add New Experience Data</a>
                    </div>
                </div>
            </div>
            
             <div class="card-body text-center">
                 <div class="row">
                    <table id="ApplicantExperiencTable" class="table table-striped table-bordered " style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Employer Name</th>
                                <th>Position</th>
                                <th>Start Date</th>
                                <th>End Date</th>
                                <th></th>

                            </tr>
        
                        </thead>
                        <tbody>

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

CareJobApplicationv2/Views/ApplicantBrofiles/_ApplicantQ1Answers.cshtml
<div class="row text-center mt-5 mb-5">
    

</div>
<div class="row">
    


    
    <div class="col-lg-12">
        <div class="card mb-4">
            <div class="card-header">
                <div class="row">
                    <div class="col-sm-8">
                        <h5 >Referee</h5>
                    </div>
                    <div class="col-sm-4 text-right">
                        <a class="btn btn-sm btn-success" onclick="PopupForm('@Url.Action("AddApplicantQ1","ApplicantBrofiles")','Education Data')"><i class="fas fa-plus" ></i> Answer Details</a>
                    </div>
                </div>
            </div>
            
             <div class="card-body text-center">
                 <div class="row">
                    <table id="ApplicantQ1Table" class="table table-striped table-bordered " style="width:100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>PersonNameEn</th>
                                <th>personNameAr</th>
                                <th>RelationType</th>
                                
                                <th></th>

                            </tr>
        
                        </thead>
                        <tbody>

                        </tbody>

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

CareJobApplicationv2/Views/ApplicantBrofiles/_EditApplicantComputerSkills.cshtml
@model CareJobApplicationv2.Models.ApplicantComputerSkills

@{
    ViewData["Title"] = "Create";
    // Layout = "~/Views/Shared/_AdminLayout.cshtml";
    Layout = null;
}


<div class="row">
    <div class="col-md-12">
        <form asp-action="EditApplicantComputerSkill" method="post" onsubmit="return SubmitForm(this,'ApplicantComputerSkills')">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"  />
            <div class="row mt-5 mb-5">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label asp-for="SkillId" class="control-label"></label>
                        <select asp-for="SkillId" class="form-control" asp-items="ViewBag.SkillId"></select>
                    </div>
                </div>

                <div class="col-lg-6 mb-3">
                    <div class="form-group">
                        <label asp-for="SkillLevelId" class="control-label"></label>
                        <select asp-for="SkillLevelId" class="form-control" asp-items="ViewBag.SkillLevelId"></select>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}